# Copyright(C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

init_image: "rocm/pytorch:rocm6.4.3_ubuntu24.04_py3.12_pytorch_release_2.6.0"
x11_display: false

build_arguments:            
- "HSA_OVERRIDE_GFX_VERSION=11.0.0"  

environment_variables:             
- "HSA_OVERRIDE_GFX_VERSION=11.0.0"  
      
port_mappings:
- "8888:8888"  
    